# .travis.yml

dist: bionic

# build using Python 3.6
language: python
python:
  - 3.8
# Cache Dependencies
cache: pip
# we need two Linux packages for the optimize_images plugin
#addons:
#  apt:
#    packages:
#    - optipng
#    - libjpeg-progs

# install dependencies
install:
  - sudo apt update -y
  - sudo apt upgrade -y
  - sudo apt install python git make python3-venv
  - pip install --upgrade pip
  - pip install markdown

# build our blog
script:
  - mkdir build
  - cd build
  - virtualenv -p python3.8.1 VENV
  - source VENV/bin/activate
  - pip install pelican markdown
  - git clone https://github.com/iacchus/iacchus.github.io
  - git clone https://github.com/iacchus/iacchus.github.io-pelican
  - cd iacchus.github.io-pelican
  - make clean
  - chmod +x build.sh
  - PYTHONPATH=~/build/iacchus.github.io-pelican ./build.sh

deploy:
  repo: iacchus/iacchus.github.io
  local_dir: ../iacchus.github.io
  target-branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
